
pipeline:
  test-moeserifu-release:
    image: gcc:5
    commands:
      - make
      - make clean
    when:
      event: [pull_request, push]
      branch: master

  test-moeserifu-debug:
    image: gcc:5
    commands:
      - make debug
      - make clean
    when:
      event: [pull_request, push]
      branch: master

  test-plugins-release:
    image: gcc:5
    commands:
      - make plugins
      - make clean-plugins
    when:
      event: [pull_request, push]
      branch: master

  test-plugins-debug:
    image: gcc:5
    commands:
      - make debug plugins
      - make clean
    when:
      event: [pull_request, push]
      branch: master

  run-python-tests:
    image: python:3
    environment:
      TEST=1
    commands:
      - cd python
      - pip install poetry
      - poetry install 
      - ./test_and_coverage.sh
    when:
      event: [pull_request, push]
      branch: master

